name: "hello world"
on:
  push:
    branches: [main]
jobs:
  say-hello:
    run-on: mac-latest
    steps:
      - run: echo "action_state=yellow" >> "$GITHUB_ENV"
      - run: echo Hello world, today is $action_state